<template>
	<div>
		<h2>
			<font-awesome-icon :icon="['fas', 'user-friends']" class="mr-2" /> Management Users
		</h2>
		<div class="row">
			<div class="col">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero ut vel earum eaque doloremque, delectus eum rem ex, quam quae quos suscipit nostrum mollitia iste corrupti cumque voluptate labore dolor!
			</div>
		</div>

		<!-- modal -->
    <b-modal title="Merchant Registration" v-model="modalAddMerchant" size="sm">
			<div>
			  <div class="form-group">
			    <input type="text" class="form-control" placeholder="Enter name">
			  </div>
			  <div class="form-group">
			    <input type="text" class="form-control" placeholder="Enter username">
			  </div>
			  <div class="form-group">
			    <input type="email" class="form-control" placeholder="Enter email">
			  </div>
			  <div class="form-group mb-1">
			    <input type="text" class="form-control" placeholder="Enter mobile">
			  </div>
			  <!-- <div class="form-group">
			    <input type="text" readonly class="form-control-plaintext" value="password is autogenerated">
			  </div> -->
			  <!-- <div class="form-group mb-1">
			    <input type="password" class="form-control" placeholder="Enter Password" v-model="addMerchant.password">
			  </div> -->
			</div>
			<div slot="modal-footer" class="w-100 text-center">
			 	<button type="button" class="btn btn-primary mr-2">Register</button>
			 	<button type="button" class="btn btn-default">Cancel</button>
			</div>
    </b-modal>
	</div>
</template>

<script>
import axios from 'axios'

export default {
	data() {
		return {
			// 
		}
	},
	methods: {
		/**
		 * Open a modal
		 * 
		 * @param  {[type]} type
		 * @param  {[type]} data 'Object of data'
		 */
		openModal(type, data) {
			let vm = this
			switch(type) {
				case '':
					break
				default: //
			}
		},
	}
}
</script>