<template>
	<div>
		<h2>
			<font-awesome-icon :icon="['fas', 'store']" class="mr-2" /> Merchant
			<a href="#" class="btn btn-secondary float-right" @click="openModal('AddMerchant')">&plus; Add a merchant</a>
		</h2>
		<div class="row">
			<div class="col">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero ut vel earum eaque doloremque, delectus eum rem ex, quam quae quos suscipit nostrum mollitia iste corrupti cumque voluptate labore dolor!
			</div>
		</div>

		<!-- modal -->
    <b-modal title="Merchant Registration" v-model="modalAddMerchant" size="sm">
			<div>
			  <div class="form-group">
			    <input type="text" class="form-control" placeholder="Enter name" v-model="addMerchant.name">
			  </div>
			  <div class="form-group">
			    <input type="text" class="form-control" placeholder="Enter username" v-model="addMerchant.username">
			  </div>
			  <div class="form-group">
			    <input type="email" class="form-control" placeholder="Enter email" v-model="addMerchant.email">
			  </div>
			  <div class="form-group mb-1">
			    <input type="text" class="form-control" placeholder="Enter mobile" v-model="addMerchant.mobileNumber">
			  </div>
			  <!-- <div class="form-group">
			    <input type="text" readonly class="form-control-plaintext" value="password is autogenerated">
			  </div> -->
			  <!-- <div class="form-group mb-1">
			    <input type="password" class="form-control" placeholder="Enter Password" v-model="addMerchant.password">
			  </div> -->
			</div>
			<div slot="modal-footer" class="w-100 text-center">
			 	<button type="button" class="btn btn-primary mr-2" @click="register">Register</button>
			 	<button type="button" class="btn btn-default" @click="modalAddMerchant=false">Cancel</button>
			</div>
    </b-modal>
	</div>
</template>

<script>
// note:
// 1. validation
// 2. sweet alert

import axios from 'axios'

export default {
	data() {
		return {
			// Merchant registration
			modalAddMerchant: false,
			addMerchant: {}
		}
	},
	methods: {
		/**
		 * Open a modal
		 * @param  {[type]} type
		 * @param  {[type]} data 'Object of data'
		 */
		openModal(type, data) {
			let vm = this
			switch(type) {
				case 'AddMerchant':
					vm.addMerchant = {}
					vm.modalAddMerchant = true
					break
				default: //
			}
		},

		/**
		 * Merchant Registration
		 */
		register() {
			let vm = this
			axios.post(`${process.env.VUE_APP_API_URL}/api/merchants`, vm.addMerchant, 
				{
					headers: {
            'Authorization': process.env.VUE_APP_AUTHORIZATION,
            'Content-Type': 'application/json',
            'x-access-token': localStorage.getItem('auth_token')
					}
				}).then(res => {
					alert('Successfully registered!')
					vm.modalAddMerchant = false
				})
		}
	}
}
</script>